name: unfocus_widget
description: Useful widget for unfocusing the TextField when touching outside
version: 0.0.5
homepage: https://tungbach.netlify.app/
repository: https://github.com/thomas-p95/unfocus_widget
issue_tracker: https://github.com/thomas-p95/unfocus_widget/issues
environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
flutter:
