name: unfocus_widget
description: Useful widget for unfocusing the TextField when touching outside
version: 0.1.2
homepage: https://tungpt.netlify.app/
repository: https://github.com/thomas-p95/unfocus_widget
issue_tracker: https://github.com/thomas-p95/unfocus_widget/issues
environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^7.5.1
  very_good_analysis: ^10.2.0

melos:
  repository: https://github.com/thomas-p95/unfocus_widget
  sdkPath: .fvm/flutter_sdk
  useRootAsPackage: true
  ide:
    intellij:
      enabled: false
  command:
    version:
      includeCommitId: true
      linkToCommits: true
      includeScopes: true
      workspaceChangelog: false
      changelogCommitBodies:
        include: true
        onlyBreaking: false
      message: "chore(release): Version{new_package_versions} \U0001F389"
